# environment.yml
name: cs_ftmle
channels:
    - conda-forge
    - defaults

dependencies:
    - python=3.7
    - pip
    # Core specific python
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - beautifulsoup4
    # NLP
    - nltk
    - textblob
    # Jupyter environment
    - autopep8
    - jupyterlab
    - notebook
    - ipython
    - jupyter_contrib_nbextensions
    - nbclean
    # Autograding
    - matplotcheck=0.0.11
    - nbgrader
    # Machine Learning
    - scikit-learn
    # Deep learning
    - tensorflow 2.4.1
    # Streamlit
    - streamlit
